name: Format
on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'

      - name: Add JuliaFormatter and format
        run: |
          julia --color=yes -e '
            using Pkg; Pkg.add("JuliaFormatter");
            using JuliaFormatter;
            format(".");'
      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -am "chore: format with JuliaFormatter"
            git push
          fi